export const PART1_CREATE_REQUEST="PART1_CREATE_REQUEST"
export const PART1_CREATE_SUCCESS="PART1_CREATE_SUCCESS"
export const PART1_CREATE_FAIL="PART1_CREATE_FAIL"

export const PART2_CREATE_REQUEST="PART2_CREATE_REQUEST"
export const PART2_CREATE_SUCCESS="PART2_CREATE_SUCCESS"
export const PART2_CREATE_FAIL="PART2_CREATE_FAIL"

export const PART3_CREATE_REQUEST="PART3_CREATE_REQUEST"
export const PART3_CREATE_SUCCESS="PART3_CREATE_SUCCESS"
export const PART3_CREATE_FAIL="PART3_CREATE_FAIL"

export const PART4_CREATE_REQUEST="PART4_CREATE_REQUEST"
export const PART4_CREATE_SUCCESS="PART4_CREATE_SUCCESS"
export const PART4_CREATE_FAIL="PART4_CREATE_FAIL"

export const PART5_CREATE_REQUEST="PART5_CREATE_REQUEST"
export const PART5_CREATE_SUCCESS="PART5_CREATE_SUCCESS"
export const PART5_CREATE_FAIL="PART5_CREATE_FAIL"

export const PART1_GET_REQUEST="PART1_GET_REQUEST"
export const PART1_GET_SUCCESS="PART1_GET_SUCCESS"
export const PART1_GET_FAIL="PART1_GET_FAIL"
export const PART1_GET_RESET="PART1_GET_RESET"

export const PART2_GET_REQUEST="PART2_GET_REQUEST"
export const PART2_GET_SUCCESS="PART2_GET_SUCCESS"
export const PART2_GET_FAIL="PART2_GET_FAIL"
export const PART2_GET_RESET="PART2_GET_RESET"


export const PART3_GET_REQUEST="PART3_GET_REQUEST"
export const PART3_GET_SUCCESS="PART3_GET_SUCCESS"
export const PART3_GET_FAIL="PART3_GET_FAIL"
export const PART3_GET_RESET="PART3_GET_RESET"


export const PART4_GET_REQUEST="PART4_GET_REQUEST"
export const PART4_GET_SUCCESS="PART4_GET_SUCCESS"
export const PART4_GET_FAIL="PART4_GET_FAIL"
export const PART4_GET_RESET="PART4_GET_RESET"


export const PART5_GET_REQUEST="PART5_GET_REQUEST"
export const PART5_GET_SUCCESS="PART5_GET_SUCCESS"
export const PART5_GET_FAIL="PART5_GET_FAIL"
export const PART5_GET_RESET="PART5_GET_RESET"

export const MY_PART5_GET_REQUEST="MY_PART5_GET_REQUEST"
export const MY_PART5_GET_SUCCESS="MY_PART5_GET_SUCCESS"
export const MY_PART5_GET_FAIL="MY_PART5_GET_FAIL"
export const MY_PART5_GET_RESET="MY_PART5_GET_RESET"
