# Generated by Django 3.2 on 2022-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220530_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part1',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
