# Generated by Django 3.2 on 2022-06-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220603_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part5',
            old_name='paymentMethod',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='part5',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='part5',
            name='number_pages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='part5',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=200, null=True),
        ),
    ]
