# Generated by Django 3.2 on 2022-06-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220607_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part5',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='part5',
            name='part2',
        ),
        migrations.RemoveField(
            model_name='part5',
            name='part3',
        ),
        migrations.RemoveField(
            model_name='part5',
            name='part4',
        ),
    ]
